"""
Infra Agent tools.
"""

from .docker_tools import (
    docker_build,
    docker_compose_down,
    docker_compose_logs,
    docker_compose_ps,
    docker_compose_restart,
    docker_compose_up,
    docker_exec,
    docker_health_check,
    docker_images,
    docker_inspect,
    docker_logs,
    docker_ps,
    docker_pull,
    docker_stats,
    docker_system_prune,
)
from .nginx_tools import (
    nginx_create_site,
    nginx_disable_site,
    nginx_enable_site,
    nginx_read_site_config,
    nginx_reload,
    nginx_status,
    nginx_test_config,
    nginx_view_logs,
)
from .ssl_tools import (
    check_certificate,
    list_certificates,
    renew_certificate,
    request_certificate,
)
from .domain_tools import (
    get_domain_status,
    list_domains,
    provision_domain,
    remove_domain,
    verify_domain,
)
from .cloudflare_tools import (
    cf_create_dns_record,
    cf_delete_dns_record,
    cf_get_analytics,
    cf_get_zone,
    cf_list_dns_records,
    cf_list_zones,
    cf_purge_cache,
    cf_set_ssl_mode,
    cf_update_dns_record,
)
from .systemd_tools import (
    systemd_create_service,
    systemd_create_timer,
    systemd_daemon_reload,
    systemd_disable,
    systemd_enable,
    systemd_get_status,
    systemd_list_timers,
    systemd_list_units,
    systemd_read_unit_file,
    systemd_reload,
    systemd_restart,
    systemd_start,
    systemd_stop,
    systemd_view_logs,
)
from .monitoring_tools import (
    check_port,
    scan_ports,
    get_network_connections,
    get_network_stats,
    get_disk_io,
    search_logs,
    tail_log,
    check_dns,
    ping_host,
)

__all__ = [
    # Docker tools
    "docker_ps",
    "docker_logs",
    "docker_exec",
    "docker_inspect",
    "docker_compose_ps",
    "docker_compose_up",
    "docker_compose_down",
    "docker_compose_restart",
    "docker_compose_logs",
    "docker_images",
    "docker_pull",
    "docker_build",
    "docker_stats",
    "docker_health_check",
    "docker_system_prune",
    # Nginx tools
    "nginx_status",
    "nginx_test_config",
    "nginx_reload",
    "nginx_read_site_config",
    "nginx_create_site",
    "nginx_enable_site",
    "nginx_disable_site",
    "nginx_view_logs",
    # SSL tools
    "list_certificates",
    "check_certificate",
    "request_certificate",
    "renew_certificate",
    # Domain tools
    "list_domains",
    "get_domain_status",
    "provision_domain",
    "remove_domain",
    "verify_domain",
    # Cloudflare tools
    "cf_list_zones",
    "cf_get_zone",
    "cf_list_dns_records",
    "cf_create_dns_record",
    "cf_update_dns_record",
    "cf_delete_dns_record",
    "cf_purge_cache",
    "cf_set_ssl_mode",
    "cf_get_analytics",
    # Systemd tools
    "systemd_list_units",
    "systemd_get_status",
    "systemd_start",
    "systemd_stop",
    "systemd_restart",
    "systemd_reload",
    "systemd_enable",
    "systemd_disable",
    "systemd_daemon_reload",
    "systemd_view_logs",
    "systemd_read_unit_file",
    "systemd_create_service",
    "systemd_create_timer",
    "systemd_list_timers",
    # Monitoring tools
    "check_port",
    "scan_ports",
    "get_network_connections",
    "get_network_stats",
    "get_disk_io",
    "search_logs",
    "tail_log",
    "check_dns",
    "ping_host",
]
