"""
AI Core Package - Shared utilities for AI Infrastructure.

This package provides common functionality used across all services:
- Configuration management
- Structured logging
- Custom exceptions
- Prometheus metrics
- Circuit breaker pattern
"""

from .circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitOpenError,
    circuit_breaker,
    get_all_breaker_status,
    get_circuit_breaker,
    reset_circuit_breaker,
)
from .cost_tracker import (
    CostTracker,
    DailyUsage,
    UsageSummary,
    configure_cost_tracker,
    get_cost_tracker,
)
from .pricing import (
    MODEL_PRICING,
    Provider,
    UsageCost,
    calculate_cost,
    estimate_cost,
    format_cost,
    get_model_pricing,
    get_model_provider,
)
from .enums import (
    AgentStatus,
    AgentType,
    CapabilityCategory,
    DomainStatus,
    ElevationReason,
    MessageType,
    PermissionLevel,
    TaskStatus,
)
from .config import (
    APISettings,
    AWSSettings,
    DatabaseSettings,
    LoggingSettings,
    QdrantSettings,
    RedisSettings,
    Settings,
    get_settings,
    reload_settings,
)
from .exceptions import (
    AIInfraError,
    AgentBusyError,
    AgentError,
    AgentNotFoundError,
    AgentTimeoutError,
    APIError,
    AuthError,
    ConfigurationError,
    DatabaseConnectionError,
    DatabaseError,
    DuplicateError,
    EmbeddingError,
    ExternalServiceError,
    InvalidConfigError,
    InvalidInputError,
    InvalidTokenError,
    MemoryError,
    MissingConfigError,
    NotFoundError,
    PermissionDeniedError,
    QueryError,
    RateLimitError,
    ServiceUnavailableError,
    StorageError,
    TaskCancelledError,
    TaskError,
    TaskFailedError,
    UnauthorizedError,
    ValidationError,
)
from .logging import (
    configure_logging,
    get_correlation_id,
    get_logger,
    set_correlation_id,
)
from .permissions import (
    ElevationGrant,
    ElevationManager,
    ElevationRecord,
    ElevationRequest,
    PermissionContext,
    get_elevation_manager,
)
from .security import (
    SecurityAction,
    SecurityConfig,
    SecurityValidator,
    SecurityViolation,
    ThreatLevel,
    get_security_validator,
    validate_tool,
)
from .plugins import (
    HookEvent,
    Plugin,
    PluginHook,
    PluginRegistry,
    PluginStatus,
    PluginTool,
    MCPServerConfig,
    get_plugin_registry,
    init_plugins,
)
from .llm_provider import (
    LLMProviderType,
    LLMResponse,
    LLMToolCall,
    LLMToolResult,
)
from .llm_client import LLMClient
from .model_selector import ModelTier, select_model
from .mcp_client import (
    MCPClient,
    MCPToolResult,
    get_mcp_client,
    init_mcp_servers,
)
from .plugin_integration import (
    PluginIntegration,
    get_plugin_integration,
    init_agent_plugins,
)
from .metrics import (
    agent_active_tasks,
    agent_errors_total,
    agent_task_duration_seconds,
    agent_tasks_total,
    agent_tool_calls_total,
    app_info,
    claude_api_cost_dollars,
    claude_api_tokens_total,
    db_connections_active,
    db_connections_idle,
    db_errors_total,
    db_query_duration_seconds,
    embedding_generation_duration_seconds,
    external_api_duration_seconds,
    external_api_errors_total,
    external_api_requests_total,
    http_request_duration_seconds,
    http_requests_in_progress,
    http_requests_total,
    memory_items_count,
    memory_operation_duration_seconds,
    memory_operations_total,
    message_processing_duration_seconds,
    message_queue_length,
    messages_consumed_total,
    messages_published_total,
    pai_learnings_extracted_total,
    pai_phase_duration_seconds,
    pai_phase_executions_total,
    system_uptime_seconds,
)

__version__ = "0.1.0"

__all__ = [
    # Version
    "__version__",
    # Enums
    "TaskStatus",
    "AgentType",
    "AgentStatus",
    "MessageType",
    "DomainStatus",
    "PermissionLevel",
    "CapabilityCategory",
    "ElevationReason",
    # Config
    "Settings",
    "DatabaseSettings",
    "RedisSettings",
    "QdrantSettings",
    "APISettings",
    "AWSSettings",
    "LoggingSettings",
    "get_settings",
    "reload_settings",
    # Logging
    "configure_logging",
    "get_logger",
    "get_correlation_id",
    "set_correlation_id",
    # Exceptions
    "AIInfraError",
    "ConfigurationError",
    "MissingConfigError",
    "InvalidConfigError",
    "DatabaseError",
    "DatabaseConnectionError",
    "QueryError",
    "NotFoundError",
    "DuplicateError",
    "AgentError",
    "AgentNotFoundError",
    "AgentBusyError",
    "AgentTimeoutError",
    "PermissionDeniedError",
    "ExternalServiceError",
    "APIError",
    "RateLimitError",
    "ServiceUnavailableError",
    "AuthError",
    "InvalidTokenError",
    "UnauthorizedError",
    "ValidationError",
    "InvalidInputError",
    "TaskError",
    "TaskCancelledError",
    "TaskFailedError",
    "MemoryError",
    "EmbeddingError",
    "StorageError",
    # Circuit Breaker
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitOpenError",
    "circuit_breaker",
    "get_all_breaker_status",
    "get_circuit_breaker",
    "reset_circuit_breaker",
    # Pricing & Cost Tracking
    "Provider",
    "UsageCost",
    "MODEL_PRICING",
    "calculate_cost",
    "estimate_cost",
    "format_cost",
    "get_model_pricing",
    "get_model_provider",
    "CostTracker",
    "UsageSummary",
    "DailyUsage",
    "get_cost_tracker",
    "configure_cost_tracker",
    # Permissions
    "PermissionContext",
    "ElevationRequest",
    "ElevationGrant",
    "ElevationRecord",
    "ElevationManager",
    "get_elevation_manager",
    # Security
    "SecurityAction",
    "SecurityConfig",
    "SecurityValidator",
    "SecurityViolation",
    "ThreatLevel",
    "get_security_validator",
    "validate_tool",
    # Metrics
    "app_info",
    "http_requests_total",
    "http_request_duration_seconds",
    "http_requests_in_progress",
    "agent_tasks_total",
    "agent_task_duration_seconds",
    "agent_active_tasks",
    "agent_errors_total",
    "agent_tool_calls_total",
    "db_connections_active",
    "db_connections_idle",
    "db_query_duration_seconds",
    "db_errors_total",
    "external_api_requests_total",
    "external_api_duration_seconds",
    "external_api_errors_total",
    "claude_api_tokens_total",
    "claude_api_cost_dollars",
    "memory_operations_total",
    "memory_operation_duration_seconds",
    "memory_items_count",
    "embedding_generation_duration_seconds",
    "messages_published_total",
    "messages_consumed_total",
    "message_processing_duration_seconds",
    "message_queue_length",
    "pai_phase_executions_total",
    "pai_phase_duration_seconds",
    "pai_learnings_extracted_total",
    "system_uptime_seconds",
    # Plugins
    "Plugin",
    "PluginTool",
    "PluginHook",
    "PluginStatus",
    "PluginRegistry",
    "HookEvent",
    "MCPServerConfig",
    "get_plugin_registry",
    "init_plugins",
    # LLM Provider
    "LLMClient",
    "LLMProviderType",
    "LLMResponse",
    "LLMToolCall",
    "LLMToolResult",
    # Model Selection
    "ModelTier",
    "select_model",
    # MCP Client
    "MCPClient",
    "MCPToolResult",
    "get_mcp_client",
    "init_mcp_servers",
    # Plugin Integration
    "PluginIntegration",
    "get_plugin_integration",
    "init_agent_plugins",
]
