"""
QA Agent tools.
"""

from .review_tools import (
    analyze_code_quality,
    check_dependencies,
    review_changes,
)
from .security_tools import (
    check_secrets,
    scan_dependencies,
    validate_permissions,
)
from .test_tools import (
    list_tests,
    run_coverage,
    run_lint,
    run_tests,
)
from .type_checking_tools import (
    run_mypy,
    check_type_coverage,
    run_ruff,
)
from .api_test_tools import (
    test_api_endpoint,
    test_api_batch,
    validate_json_schema,
    measure_api_performance,
    check_api_health,
)

# Browser automation tools
from .browser_tools import (
    browser_launch,
    browser_close,
    browser_close_all,
    browser_list,
    browser_context_create,
    browser_context_close,
    page_new,
    page_close,
    page_goto,
    page_reload,
    page_go_back,
    page_go_forward,
    page_get_url,
    page_get_title,
    page_get_content,
    page_wait_for_selector,
    page_wait_for_load_state,
    page_wait_for_url,
    page_evaluate,
)
from .browser_actions import (
    element_click,
    element_dblclick,
    element_hover,
    element_fill,
    element_type,
    element_clear,
    element_press,
    element_focus,
    element_select_option,
    element_check,
    element_uncheck,
    element_drag_drop,
    element_upload_file,
    element_query,
    element_query_all,
    element_count,
    element_get_text,
    element_get_attribute,
    element_is_visible,
    element_is_enabled,
)
from .browser_assertions import (
    expect_element_visible,
    expect_element_hidden,
    expect_element_enabled,
    expect_element_text,
    expect_element_value,
    expect_element_attribute,
    expect_page_url,
    expect_page_title,
    expect_element_count,
    expect_element_checked,
    expect_element_focused,
)
from .browser_capture import (
    screenshot_page,
    screenshot_element,
    video_start,
    video_stop,
    trace_start,
    trace_stop,
    pdf_export,
)
from .browser_network import (
    network_intercept_enable,
    network_mock_response,
    network_mock_json,
    network_block_urls,
    network_get_requests,
    network_wait_for_response,
    network_wait_for_request,
    network_clear_interceptors,
)
from .browser_auth import (
    credential_store_tool,
    credential_get,
    credential_rotate,
    credential_list,
    credential_delete,
    auth_login,
    auth_logout,
    auth_save_session,
    auth_load_session,
    auth_list_sessions,
    auth_delete_session,
)

__all__ = [
    # Test tools
    "run_tests",
    "list_tests",
    "run_coverage",
    "run_lint",
    # Review tools
    "review_changes",
    "analyze_code_quality",
    "check_dependencies",
    # Security tools
    "check_secrets",
    "scan_dependencies",
    "validate_permissions",
    # Type checking tools
    "run_mypy",
    "check_type_coverage",
    "run_ruff",
    # API test tools
    "test_api_endpoint",
    "test_api_batch",
    "validate_json_schema",
    "measure_api_performance",
    "check_api_health",
    # Browser lifecycle tools
    "browser_launch",
    "browser_close",
    "browser_close_all",
    "browser_list",
    "browser_context_create",
    "browser_context_close",
    "page_new",
    "page_close",
    "page_goto",
    "page_reload",
    "page_go_back",
    "page_go_forward",
    "page_get_url",
    "page_get_title",
    "page_get_content",
    "page_wait_for_selector",
    "page_wait_for_load_state",
    "page_wait_for_url",
    "page_evaluate",
    # Browser action tools
    "element_click",
    "element_dblclick",
    "element_hover",
    "element_fill",
    "element_type",
    "element_clear",
    "element_press",
    "element_focus",
    "element_select_option",
    "element_check",
    "element_uncheck",
    "element_drag_drop",
    "element_upload_file",
    "element_query",
    "element_query_all",
    "element_count",
    "element_get_text",
    "element_get_attribute",
    "element_is_visible",
    "element_is_enabled",
    # Browser assertion tools
    "expect_element_visible",
    "expect_element_hidden",
    "expect_element_enabled",
    "expect_element_text",
    "expect_element_value",
    "expect_element_attribute",
    "expect_page_url",
    "expect_page_title",
    "expect_element_count",
    "expect_element_checked",
    "expect_element_focused",
    # Browser capture tools
    "screenshot_page",
    "screenshot_element",
    "video_start",
    "video_stop",
    "trace_start",
    "trace_stop",
    "pdf_export",
    # Browser network tools
    "network_intercept_enable",
    "network_mock_response",
    "network_mock_json",
    "network_block_urls",
    "network_get_requests",
    "network_wait_for_response",
    "network_wait_for_request",
    "network_clear_interceptors",
    # Browser auth tools
    "credential_store_tool",
    "credential_get",
    "credential_rotate",
    "credential_list",
    "credential_delete",
    "auth_login",
    "auth_logout",
    "auth_save_session",
    "auth_load_session",
    "auth_list_sessions",
    "auth_delete_session",
]
